# Series

In [2]:
import pandas as pd
import numpy as np

In [3]:
labels = ['a', 'b', 'c'] ## Isso é uma lista

minha_lista = list((10,20,30)) ## Isso também é uma lista, sendo criada por meio da função "list()"

arr = np.array([10,20,30]) ## Isso transforma a lista em um array numpy

d = {'a': 10, 'b': 20, 'c': 30}

In [4]:
pd.Series(labels) ## Criando uma series a partir de uma lista padrão do python

0    a
1    b
2    c
dtype: str

In [5]:
pd.Series(data=labels, index=minha_lista) ## Posso manipular a criação dos indíces da minha series a partir de seus parâmetros

10    a
20    b
30    c
dtype: str

In [6]:
pd.Series(labels, minha_lista) 
## Eu também não preciso dizer os parâmetros se eles estiverem na mesma ordem padrão da assinatura da função.

10    a
20    b
30    c
dtype: str

In [7]:
d ## A minha variável D é um dicionário

{'a': 10, 'b': 20, 'c': 30}

In [8]:
pd.Series(d) ## Quando eu passei um dicionário pra criar uma series ele já inferiu que as 'chaves' do dicionário seriam os índices da series

a    10
b    20
c    30
dtype: int64

In [9]:
series1 = pd.Series([1,2,3,4], index=['Alemanha','Rússia','Estados Unidos','Japão'])
series1

Alemanha          1
Rússia            2
Estados Unidos    3
Japão             4
dtype: int64

In [10]:
series2 = pd.Series([1,2,5,4], index=['Alemanha','Rússia','Itália','Japão'])
series2

Alemanha    1
Rússia      2
Itália      5
Japão       4
dtype: int64

In [11]:
series1 + series2

Alemanha          2.0
Estados Unidos    NaN
Itália            NaN
Japão             8.0
Rússia            4.0
dtype: float64

# Dataframe

In [12]:
import numpy as np
import pandas as pd

from numpy.random import randn

In [13]:
df = pd.DataFrame(randn(5, 4), index=["A", "B", "C", "D", "E"], columns="W X Y Z".split())
df

          W         X         Y         Z
A -1.065599  1.264993  1.109647  1.328049
B -0.268977  1.676715  0.056672  0.182012
C  0.347921  0.137316 -0.825532  0.814184
D  1.341553  0.033174  0.982162  0.213017
E  0.854507  2.405024  0.012024 -0.449290

In [14]:
print(df["W"])
type(df["W"])

A   -1.065599
B   -0.268977
C    0.347921
D    1.341553
E    0.854507
Name: W, dtype: float64

pandas.Series

In [15]:
print(df[["W", "Y"]])
type(df[["W", "Y"]])

          W         Y
A -1.065599  1.109647
B -0.268977  0.056672
C  0.347921 -0.825532
D  1.341553  0.982162
E  0.854507  0.012024

pandas.DataFrame

In [16]:
df["Novo"] = df["W"]
df

          W         X         Y         Z      Novo
A -1.065599  1.264993  1.109647  1.328049 -1.065599
B -0.268977  1.676715  0.056672  0.182012 -0.268977
C  0.347921  0.137316 -0.825532  0.814184  0.347921
D  1.341553  0.033174  0.982162  0.213017  1.341553
E  0.854507  2.405024  0.012024 -0.449290  0.854507

In [17]:
df["Novo"] = df["X"] + df ["Y"]
df

          W         X         Y         Z      Novo
A -1.065599  1.264993  1.109647  1.328049  2.374639
B -0.268977  1.676715  0.056672  0.182012  1.733388
C  0.347921  0.137316 -0.825532  0.814184 -0.688216
D  1.341553  0.033174  0.982162  0.213017  1.015336
E  0.854507  2.405024  0.012024 -0.449290  2.417049

In [18]:
df["Novo"].drop("A", axis=0) ## Função de DROP similar a cláusula do SQL
## Nesse caso ao fazer df["Novo"] eu estou convertendo e selecionando uma series do meu Dataframe, ao dizer drop("A", axis=0), eu estou selecionando para dropar o índice A eixo 0 que é exatamente a 1ª posição da 1ª (e única coluna)

df[["Novo"]].drop("Novo", axis=1)
# Agora eu preservei o objeto Dataframe porque eu selecionei a coluna "Novo" dentro de uma matriz
# Ao dropar "Novo" eu estou selecionando a coluna toda e o eixo 1 é o eixo das colunas

#df[["Novo"]].drop("Novo", axis=0) -> Não funciona porque axis=0 são os índices pra um DF, não existe o índice "Novo" nesse conjunto de dados, apenas A, B, C...

df[["Novo"]].drop("A", axis=0)
# axis=0 seleciona os índices de um DF, logo, eu consigo acessar e dropar o índice A ou B ou C ou D etc

       Novo
B  1.733388
C -0.688216
D  1.015336
E  2.417049

In [19]:
df ## O Dataframe original não sofreu mudanças porque o drop foi apenas executado pra gerar output e não foi armazenado em nenhuma variável, incluindo a original

          W         X         Y         Z      Novo
A -1.065599  1.264993  1.109647  1.328049  2.374639
B -0.268977  1.676715  0.056672  0.182012  1.733388
C  0.347921  0.137316 -0.825532  0.814184 -0.688216
D  1.341553  0.033174  0.982162  0.213017  1.015336
E  0.854507  2.405024  0.012024 -0.449290  2.417049

In [20]:
df.drop("A", axis=0, inplace=True)
df
# O parâmetro inplace vai manipular se estou alterando no DF original ou não, caso não queira usar uma nova variável

          W         X         Y         Z      Novo
B -0.268977  1.676715  0.056672  0.182012  1.733388
C  0.347921  0.137316 -0.825532  0.814184 -0.688216
D  1.341553  0.033174  0.982162  0.213017  1.015336
E  0.854507  2.405024  0.012024 -0.449290  2.417049

In [21]:
df.loc[["B"]] # Consigo selecionar/localizar/extrair partes específicas assim também

          W         X         Y         Z      Novo
B -0.268977  1.676715  0.056672  0.182012  1.733388

In [22]:
df.iloc[0,0] # Trabalha como se fosse um localizador via "coordenada"

np.float64(-0.2689769458244753)

# ILoc e Filtros

In [23]:
df
df.loc[["E", "D"],["X", "Z"]]

          X         Z
E  2.405024 -0.449290
D  0.033174  0.213017

In [24]:
df.iloc[:-1] # O ":" denota um invtervalo e o inteiro (1, 2, -1, -2, etc) representa o ponto de início do intervalo, que vai "iterar"/exibir os dados até o fim do data frame
# Valores positivos iniciam do "começo" do DataFrame (1ª linha), valores negativos a partir do "fim" (última linha)

          W         X         Y         Z      Novo
B -0.268977  1.676715  0.056672  0.182012  1.733388
C  0.347921  0.137316 -0.825532  0.814184 -0.688216
D  1.341553  0.033174  0.982162  0.213017  1.015336

In [25]:
df.iloc[:1, :3] # Passar um segundo argumento vai denotar a segunda "coordenada" do Data Frame

          W         X         Y
B -0.268977  1.676715  0.056672

In [26]:
df.iloc[:2, 1:2] # Seleção de lista do tipo "1:2", o 1 é inclusivo e o 2 é exclusivo. Isto é, o que vem antes do ":" inclui o índice 1 e o que vem depois exclui o índice 2

          X
B  1.676715
C  0.137316

In [27]:
df > 0 # Executa uma operação de comparação matricial com um escalar

       W     X      Y      Z   Novo
B  False  True   True   True   True
C   True  True  False   True  False
D   True  True   True   True   True
E   True  True   True  False   True

In [28]:
df[df > 0]
# Eu consigo também fazer seleções que levem em conta comparações lógicas e, além disso, usar dataframes pra selecionar dataframes
# O que tá acontecendo aqui é que o "df > 0" está retornando um dataframe com true e false e o "df[]" está usando isso pra saber que valores selecionar e quais não selecionar

          W         X         Y         Z      Novo
B       NaN  1.676715  0.056672  0.182012  1.733388
C  0.347921  0.137316       NaN  0.814184       NaN
D  1.341553  0.033174  0.982162  0.213017  1.015336
E  0.854507  2.405024  0.012024       NaN  2.417049

In [29]:
df

          W         X         Y         Z      Novo
B -0.268977  1.676715  0.056672  0.182012  1.733388
C  0.347921  0.137316 -0.825532  0.814184 -0.688216
D  1.341553  0.033174  0.982162  0.213017  1.015336
E  0.854507  2.405024  0.012024 -0.449290  2.417049

In [30]:
df["X"] > 0 # Posso fazer essa mesma manipulação com Series ao invés do dataframe todo

B    True
C    True
D    True
E    True
Name: X, dtype: bool

In [31]:
df[df["X"] > 0] # O índice E foi eliminado da seleção, pois na célula acima o E assume valor falso na comparação, o objeto dataframe está recebendo uma lista de true e false associada aos índices que ele precisa filtrar

          W         X         Y         Z      Novo
B -0.268977  1.676715  0.056672  0.182012  1.733388
C  0.347921  0.137316 -0.825532  0.814184 -0.688216
D  1.341553  0.033174  0.982162  0.213017  1.015336
E  0.854507  2.405024  0.012024 -0.449290  2.417049

# Operações com Índices

In [32]:
print(df.index) # É possível acessar o índice de um dataframe diretamente como uma lista assim
print(type(df.index))

Index(['B', 'C', 'D', 'E'], dtype='str')
<class 'pandas.Index'>

In [33]:
print(df.columns) # Idem para as colunas, ou a outra dimensão do dataframe
print(type(df.columns))
# Detalhe que tanto as colunas quanto os índices são a mesma classe Index, logo eles são o mesmo construto porém tratados como dimensões diferentes.
# Abstraindo: dimensão A e dimensão B modeladas como classe Index

Index(['W', 'X', 'Y', 'Z', 'Novo'], dtype='str')
<class 'pandas.Index'>

In [34]:
# É possível manipular qual índice é usado

# "Rebaixar" um índice a coluna
print(df.reset_index()) # Agora criou a coluna "index" e índice de fato foi adicionado como sequência numérica

print("\nIsso não grava na memória a operação:\n", df)

# É possível fazer essa mudança "inplace"
# Inplace => gravar na memória a mudança na variável (sem retorno), ao invés de executar o método e gerar um retorno
df.reset_index(inplace=True)
df

  index         W         X         Y         Z      Novo
0     B -0.268977  1.676715  0.056672  0.182012  1.733388
1     C  0.347921  0.137316 -0.825532  0.814184 -0.688216
2     D  1.341553  0.033174  0.982162  0.213017  1.015336
3     E  0.854507  2.405024  0.012024 -0.449290  2.417049

Isso não grava na memória a operação:
           W         X         Y         Z      Novo
B -0.268977  1.676715  0.056672  0.182012  1.733388
C  0.347921  0.137316 -0.825532  0.814184 -0.688216
D  1.341553  0.033174  0.982162  0.213017  1.015336
E  0.854507  2.405024  0.012024 -0.449290  2.417049

  index         W         X         Y         Z      Novo
0     B -0.268977  1.676715  0.056672  0.182012  1.733388
1     C  0.347921  0.137316 -0.825532  0.814184 -0.688216
2     D  1.341553  0.033174  0.982162  0.213017  1.015336
3     E  0.854507  2.405024  0.012024 -0.449290  2.417049

#### Obs.: sobre manipulação de índices em colunas ->

Por mais que não exista um comando "reset_columns", as colunas são índices assim como o que de fato é manipulado no reset_index.

É possível manipular os índices das colunas de duas formas:

##### Cenário 1: O "Truque da Transposição" (Literalmente resetar as colunas)
Se você quer pegar os nomes das suas colunas e transformá-los em uma linha de dados dentro do DataFrame (exatamente o que o reset_index faz com o índice das linhas), a maneira mais criativa e direta é transpor o DataFrame, resetar o índice e transpor de volta.

```python
import pandas as pd

"# Criando um DataFrame simples
df = pd.DataFrame({
    'Matemática': [90, 85],
    'História': [70, 75],
    'Física': [88, 92]
}, index=['Aluno A', 'Aluno B'])

print("--- Original ---")
print(df)

"# O TRUQUE:
"# 1. .T (Transpõe: colunas viram linhas)
"# 2. .reset_index() (O índice - antigas colunas - vira uma coluna de dados)
"# 3. .T (Transpõe de volta)
df_resetado = df.T.reset_index().T

print("\n--- Com Colunas 'Resetadas' para dentro dos dados ---")
print(df_resetado)
```

##### Cenário 2: Achatando Multi-Index (O caso mais comum)
Se você fez um groupby ou uma pivot table, provavelmente acabou com colunas hierárquicas (MultiIndex), onde você tem "níveis" de colunas (ex: ('Vendas', '2023'), ('Vendas', '2024')).

Nesse caso, o "reset" que a maioria das pessoas deseja é achatar esses níveis para ter apenas uma linha de cabeçalho simples.

```python
import pandas as pd

"# Criando um DataFrame com MultiIndex nas colunas (simulando um groupby)
cols = pd.MultiIndex.from_tuples([("Vendas", "Jan"), ("Vendas", "Fev"), ("Lucro", "Jan"), ("Lucro", "Fev")])
data = [[100, 120, 10, 12], [110, 130, 11, 13]]
df_multi = pd.DataFrame(data, columns=cols)

print("--- Original (MultiIndex) ---")
print(df_multi)

"# SOLUÇÃO: Achatar os níveis
"# Isso une os níveis com um sublinhado (ex: Vendas_Jan)
df_multi.columns = ['_'.join(col).strip() for col in df_multi.columns.values]

"# Se quiser apenas remover um nível específico (ex: ficar só com Jan/Fev e ignorar Vendas/Lucro):
"# df_multi.columns = df_multi.columns.get_level_values(1)

print("\n--- Achatado (Nível único) ---")
print(df_multi)
```

## Hierarquia de Índices e índices múltiplos

# Merge, Concat e Join

In [37]:
df1 = pd.DataFrame({'A': ['A0', 'A1','A2', 'A3'],
'B': ['B0', 'B1', 'B2', 'B3'],
'C': ['C0', 'C1', 'C2', 'C3'],
'D': ['D0', 'D1', 'D2', 'D3']},
index=[0,1,2,3])

df2 = pd.DataFrame({'A': ['A4', 'A5','A6', 'A7'],
'B': ['B4', 'B5', 'B6', 'B7'],
'C': ['C4', 'C5', 'C6', 'C7'],
'D': ['D4', 'D5', 'D6', 'D7']},
index=[4,5,6,7])

df3 = pd.DataFrame({'A': ['A8', 'A9','A10', 'A11'],
'B': ['B8', 'B9', 'B10', 'B11'],
'C': ['C8', 'C9', 'C10', 'C11'],
'D': ['D8', 'D9', 'D10', 'D11']},
index=[8,9,10,11])

In [38]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [39]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [41]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [42]:
pd.concat([df1, df2, df3]) ## Similar ao Union do SQL, Acrescentar tabelas em Power Query. Basicamente empilhar dataframes

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11