# Conceitos Básicos

## Series

In [2]:
import pandas as pd
import numpy as np

In [3]:
labels = ['a', 'b', 'c'] ## Isso é uma lista

minha_lista = list((10,20,30)) ## Isso também é uma lista, sendo criada por meio da função "list()"

arr = np.array([10,20,30]) ## Isso transforma a lista em um array numpy

d = {'a': 10, 'b': 20, 'c': 30}

In [4]:
pd.Series(labels) ## Criando uma series a partir de uma lista padrão do python

0    a
1    b
2    c
dtype: str

In [5]:
pd.Series(data=labels, index=minha_lista) ## Posso manipular a criação dos indíces da minha series a partir de seus parâmetros

10    a
20    b
30    c
dtype: str

In [6]:
pd.Series(labels, minha_lista) 
## Eu também não preciso dizer os parâmetros se eles estiverem na mesma ordem padrão da assinatura da função.

10    a
20    b
30    c
dtype: str

In [7]:
d ## A minha variável D é um dicionário

{'a': 10, 'b': 20, 'c': 30}

In [8]:
pd.Series(d) ## Quando eu passei um dicionário pra criar uma series ele já inferiu que as 'chaves' do dicionário seriam os índices da series

a    10
b    20
c    30
dtype: int64

In [9]:
series1 = pd.Series([1,2,3,4], index=['Alemanha','Rússia','Estados Unidos','Japão'])
series1

Alemanha          1
Rússia            2
Estados Unidos    3
Japão             4
dtype: int64

In [10]:
series2 = pd.Series([1,2,5,4], index=['Alemanha','Rússia','Itália','Japão'])
series2

Alemanha    1
Rússia      2
Itália      5
Japão       4
dtype: int64

In [11]:
series1 + series2

Alemanha          2.0
Estados Unidos    NaN
Itália            NaN
Japão             8.0
Rússia            4.0
dtype: float64

## Dataframe

In [12]:
import numpy as np
import pandas as pd

from numpy.random import randn

In [13]:
df = pd.DataFrame(randn(5, 4), index=["A", "B", "C", "D", "E"], columns="W X Y Z".split())
df

          W         X         Y         Z
A -0.035214  0.667055 -1.412275 -0.911250
B -1.343760  0.042888  1.339513 -1.246902
C -1.164787  1.518083  0.531966 -2.093611
D  1.345529  0.007620 -0.854077 -0.837978
E -2.888856  0.891204  0.846488 -1.273946

In [14]:
print(df["W"])
type(df["W"])

A   -0.035214
B   -1.343760
C   -1.164787
D    1.345529
E   -2.888856
Name: W, dtype: float64

pandas.Series

In [15]:
print(df[["W", "Y"]])
type(df[["W", "Y"]])

          W         Y
A -0.035214 -1.412275
B -1.343760  1.339513
C -1.164787  0.531966
D  1.345529 -0.854077
E -2.888856  0.846488

pandas.DataFrame

In [16]:
df["Novo"] = df["W"]
df

          W         X         Y         Z      Novo
A -0.035214  0.667055 -1.412275 -0.911250 -0.035214
B -1.343760  0.042888  1.339513 -1.246902 -1.343760
C -1.164787  1.518083  0.531966 -2.093611 -1.164787
D  1.345529  0.007620 -0.854077 -0.837978  1.345529
E -2.888856  0.891204  0.846488 -1.273946 -2.888856

In [17]:
df["Novo"] = df["X"] + df ["Y"]
df

          W         X         Y         Z      Novo
A -0.035214  0.667055 -1.412275 -0.911250 -0.745220
B -1.343760  0.042888  1.339513 -1.246902  1.382401
C -1.164787  1.518083  0.531966 -2.093611  2.050049
D  1.345529  0.007620 -0.854077 -0.837978 -0.846457
E -2.888856  0.891204  0.846488 -1.273946  1.737692

In [18]:
df["Novo"].drop("A", axis=0) ## Função de DROP similar a cláusula do SQL
## Nesse caso ao fazer df["Novo"] eu estou convertendo e selecionando uma series do meu Dataframe, ao dizer drop("A", axis=0), eu estou selecionando para dropar o índice A eixo 0 que é exatamente a 1ª posição da 1ª (e única coluna)

df[["Novo"]].drop("Novo", axis=1)
# Agora eu preservei o objeto Dataframe porque eu selecionei a coluna "Novo" dentro de uma matriz
# Ao dropar "Novo" eu estou selecionando a coluna toda e o eixo 1 é o eixo das colunas

#df[["Novo"]].drop("Novo", axis=0) -> Não funciona porque axis=0 são os índices pra um DF, não existe o índice "Novo" nesse conjunto de dados, apenas A, B, C...

df[["Novo"]].drop("A", axis=0)
# axis=0 seleciona os índices de um DF, logo, eu consigo acessar e dropar o índice A ou B ou C ou D etc

       Novo
B  1.382401
C  2.050049
D -0.846457
E  1.737692

In [19]:
df ## O Dataframe original não sofreu mudanças porque o drop foi apenas executado pra gerar output e não foi armazenado em nenhuma variável, incluindo a original

          W         X         Y         Z      Novo
A -0.035214  0.667055 -1.412275 -0.911250 -0.745220
B -1.343760  0.042888  1.339513 -1.246902  1.382401
C -1.164787  1.518083  0.531966 -2.093611  2.050049
D  1.345529  0.007620 -0.854077 -0.837978 -0.846457
E -2.888856  0.891204  0.846488 -1.273946  1.737692

In [20]:
df.drop("A", axis=0, inplace=True)
df
# O parâmetro inplace vai manipular se estou alterando no DF original ou não, caso não queira usar uma nova variável

          W         X         Y         Z      Novo
B -1.343760  0.042888  1.339513 -1.246902  1.382401
C -1.164787  1.518083  0.531966 -2.093611  2.050049
D  1.345529  0.007620 -0.854077 -0.837978 -0.846457
E -2.888856  0.891204  0.846488 -1.273946  1.737692

In [21]:
df.loc[["B"]] # Consigo selecionar/localizar/extrair partes específicas assim também

         W         X         Y         Z      Novo
B -1.34376  0.042888  1.339513 -1.246902  1.382401

In [22]:
df.iloc[0,0] # Trabalha como se fosse um localizador via "coordenada"

np.float64(-1.3437597822238743)

# Índices, Filtros e GroupBy

## ILoc e Filtros

In [23]:
df
df.loc[["E", "D"],["X", "Z"]]

          X         Z
E  0.891204 -1.273946
D  0.007620 -0.837978

In [24]:
df.iloc[:-1] # O ":" denota um invtervalo e o inteiro (1, 2, -1, -2, etc) representa o ponto de início do intervalo, que vai "iterar"/exibir os dados até o fim do data frame
# Valores positivos iniciam do "começo" do DataFrame (1ª linha), valores negativos a partir do "fim" (última linha)

          W         X         Y         Z      Novo
B -1.343760  0.042888  1.339513 -1.246902  1.382401
C -1.164787  1.518083  0.531966 -2.093611  2.050049
D  1.345529  0.007620 -0.854077 -0.837978 -0.846457

In [25]:
df.iloc[:1, :3] # Passar um segundo argumento vai denotar a segunda "coordenada" do Data Frame

         W         X         Y
B -1.34376  0.042888  1.339513

In [26]:
df.iloc[:2, 1:2] # Seleção de lista do tipo "1:2", o 1 é inclusivo e o 2 é exclusivo. Isto é, o que vem antes do ":" inclui o índice 1 e o que vem depois exclui o índice 2

          X
B  0.042888
C  1.518083

In [27]:
df > 0 # Executa uma operação de comparação matricial com um escalar

       W     X      Y      Z   Novo
B  False  True   True  False   True
C  False  True   True  False   True
D   True  True  False  False  False
E  False  True   True  False   True

In [28]:
df[df > 0]
# Eu consigo também fazer seleções que levem em conta comparações lógicas e, além disso, usar dataframes pra selecionar dataframes
# O que tá acontecendo aqui é que o "df > 0" está retornando um dataframe com true e false e o "df[]" está usando isso pra saber que valores selecionar e quais não selecionar

          W         X         Y   Z      Novo
B       NaN  0.042888  1.339513 NaN  1.382401
C       NaN  1.518083  0.531966 NaN  2.050049
D  1.345529  0.007620       NaN NaN       NaN
E       NaN  0.891204  0.846488 NaN  1.737692

In [29]:
df

          W         X         Y         Z      Novo
B -1.343760  0.042888  1.339513 -1.246902  1.382401
C -1.164787  1.518083  0.531966 -2.093611  2.050049
D  1.345529  0.007620 -0.854077 -0.837978 -0.846457
E -2.888856  0.891204  0.846488 -1.273946  1.737692

In [30]:
df["X"] > 0 # Posso fazer essa mesma manipulação com Series ao invés do dataframe todo

B    True
C    True
D    True
E    True
Name: X, dtype: bool

In [31]:
df[df["X"] > 0] # O índice E foi eliminado da seleção, pois na célula acima o E assume valor falso na comparação, o objeto dataframe está recebendo uma lista de true e false associada aos índices que ele precisa filtrar

          W         X         Y         Z      Novo
B -1.343760  0.042888  1.339513 -1.246902  1.382401
C -1.164787  1.518083  0.531966 -2.093611  2.050049
D  1.345529  0.007620 -0.854077 -0.837978 -0.846457
E -2.888856  0.891204  0.846488 -1.273946  1.737692

## Operações com Índices

In [32]:
print(df.index) # É possível acessar o índice de um dataframe diretamente como uma lista assim
print(type(df.index))

Index(['B', 'C', 'D', 'E'], dtype='str')
<class 'pandas.Index'>

In [33]:
print(df.columns) # Idem para as colunas, ou a outra dimensão do dataframe
print(type(df.columns))
# Detalhe que tanto as colunas quanto os índices são a mesma classe Index, logo eles são o mesmo construto porém tratados como dimensões diferentes.
# Abstraindo: dimensão A e dimensão B modeladas como classe Index

Index(['W', 'X', 'Y', 'Z', 'Novo'], dtype='str')
<class 'pandas.Index'>

In [34]:
# É possível manipular qual índice é usado

# "Rebaixar" um índice a coluna
print(df.reset_index()) # Agora criou a coluna "index" e índice de fato foi adicionado como sequência numérica

print("\nIsso não grava na memória a operação:\n", df)

# É possível fazer essa mudança "inplace"
# Inplace => gravar na memória a mudança na variável (sem retorno), ao invés de executar o método e gerar um retorno
df.reset_index(inplace=True)
df

  index         W         X         Y         Z      Novo
0     B -1.343760  0.042888  1.339513 -1.246902  1.382401
1     C -1.164787  1.518083  0.531966 -2.093611  2.050049
2     D  1.345529  0.007620 -0.854077 -0.837978 -0.846457
3     E -2.888856  0.891204  0.846488 -1.273946  1.737692

Isso não grava na memória a operação:
           W         X         Y         Z      Novo
B -1.343760  0.042888  1.339513 -1.246902  1.382401
C -1.164787  1.518083  0.531966 -2.093611  2.050049
D  1.345529  0.007620 -0.854077 -0.837978 -0.846457
E -2.888856  0.891204  0.846488 -1.273946  1.737692

  index         W         X         Y         Z      Novo
0     B -1.343760  0.042888  1.339513 -1.246902  1.382401
1     C -1.164787  1.518083  0.531966 -2.093611  2.050049
2     D  1.345529  0.007620 -0.854077 -0.837978 -0.846457
3     E -2.888856  0.891204  0.846488 -1.273946  1.737692

#### Obs.: sobre manipulação de índices em colunas ->

Por mais que não exista um comando "reset_columns", as colunas são índices assim como o que de fato é manipulado no reset_index.

É possível manipular os índices das colunas de duas formas:

##### Cenário 1: O "Truque da Transposição" (Literalmente resetar as colunas)
Se você quer pegar os nomes das suas colunas e transformá-los em uma linha de dados dentro do DataFrame (exatamente o que o reset_index faz com o índice das linhas), a maneira mais criativa e direta é transpor o DataFrame, resetar o índice e transpor de volta.

```python
import pandas as pd

"# Criando um DataFrame simples
df = pd.DataFrame({
    'Matemática': [90, 85],
    'História': [70, 75],
    'Física': [88, 92]
}, index=['Aluno A', 'Aluno B'])

print("--- Original ---")
print(df)

"# O TRUQUE:
"# 1. .T (Transpõe: colunas viram linhas)
"# 2. .reset_index() (O índice - antigas colunas - vira uma coluna de dados)
"# 3. .T (Transpõe de volta)
df_resetado = df.T.reset_index().T

print("\n--- Com Colunas 'Resetadas' para dentro dos dados ---")
print(df_resetado)
```

##### Cenário 2: Achatando Multi-Index (O caso mais comum)
Se você fez um groupby ou uma pivot table, provavelmente acabou com colunas hierárquicas (MultiIndex), onde você tem "níveis" de colunas (ex: ('Vendas', '2023'), ('Vendas', '2024')).

Nesse caso, o "reset" que a maioria das pessoas deseja é achatar esses níveis para ter apenas uma linha de cabeçalho simples.

```python
import pandas as pd

"# Criando um DataFrame com MultiIndex nas colunas (simulando um groupby)
cols = pd.MultiIndex.from_tuples([("Vendas", "Jan"), ("Vendas", "Fev"), ("Lucro", "Jan"), ("Lucro", "Fev")])
data = [[100, 120, 10, 12], [110, 130, 11, 13]]
df_multi = pd.DataFrame(data, columns=cols)

print("--- Original (MultiIndex) ---")
print(df_multi)

"# SOLUÇÃO: Achatar os níveis
"# Isso une os níveis com um sublinhado (ex: Vendas_Jan)
df_multi.columns = ['_'.join(col).strip() for col in df_multi.columns.values]

"# Se quiser apenas remover um nível específico (ex: ficar só com Jan/Fev e ignorar Vendas/Lucro):
"# df_multi.columns = df_multi.columns.get_level_values(1)

print("\n--- Achatado (Nível único) ---")
print(df_multi)
```

## Índices Multiníveis

In [130]:
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1,2,3,1,2,3]

hier_index = list(zip(outside, inside))
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [138]:
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [141]:
df = pd.DataFrame(np.random.randn(6, 2), index=hier_index, columns=['A', 'B'])
df

             A         B
G1 1  1.963442 -0.671840
   2  0.454833 -0.502509
   3  0.223461 -1.061007
G2 1 -0.354696 -0.783831
   2 -2.401179  0.280800
   3 -1.061105  0.352469

In [144]:
df.loc['G1']

          A         B
1  1.963442 -0.671840
2  0.454833 -0.502509
3  0.223461 -1.061007

In [147]:
df.loc['G1'].loc[1]

A    1.963442
B   -0.671840
Name: 1, dtype: float64

In [149]:
df.index.names = ['Grupo', 'Número']
df

                     A         B
Grupo Número
G1    1       1.963442 -0.671840
      2       0.454833 -0.502509
      3       0.223461 -1.061007
G2    1      -0.354696 -0.783831
      2      -2.401179  0.280800
      3      -1.061105  0.352469

In [151]:
df.xs(1, level='Número')

              A         B
Grupo
G1     1.963442 -0.671840
G2    -0.354696 -0.783831

In [152]:
df.xs('G1')

               A         B
Número
1       1.963442 -0.671840
2       0.454833 -0.502509
3       0.223461 -1.061007

## Group By

In [ ]:
import pandas as pd
#cria um DataFrame
datas = ({'Classe': ['Júnior','Júnior','Pleno','Pleno','Sênior','Sênior'],'Nome': ['Jorge','Carlos','Roberta','Patrícia','Bruno','Vera'],'Venda': [200, 120, 340, 124, 243, 350]})

In [ ]:
df = pd.DataFrame.from_dict(data=datas)
df

   Classe      Nome  Venda
0  Júnior     Jorge    200
1  Júnior    Carlos    120
2   Pleno   Roberta    340
3   Pleno  Patrícia    124
4  Sênior     Bruno    243
5  Sênior      Vera    350

In [7]:
grupo = df.groupby("Classe")

In [15]:
grupo.sum()

                   Nome  Venda
Classe
Júnior      JorgeCarlos    320
Pleno   RobertaPatrícia    464
Sênior        BrunoVera    593

In [17]:
grupo.min()

            Nome  Venda
Classe
Júnior    Carlos    120
Pleno   Patrícia    124
Sênior     Bruno    243

In [18]:
grupo.max()

           Nome  Venda
Classe
Júnior    Jorge    200
Pleno   Roberta    340
Sênior     Vera    350

In [23]:
df2 = df.copy()
df2

   Classe      Nome  Venda
0  Júnior     Jorge    200
1  Júnior    Carlos    120
2   Pleno   Roberta    340
3   Pleno  Patrícia    124
4  Sênior     Bruno    243
5  Sênior      Vera    350

In [25]:
df2["Venda"] = [150, 432, 190, 230, 410, 155]

In [28]:
df3 = pd.concat([df, df2])
df3

   Classe      Nome  Venda
0  Júnior     Jorge    200
1  Júnior    Carlos    120
2   Pleno   Roberta    340
3   Pleno  Patrícia    124
4  Sênior     Bruno    243
5  Sênior      Vera    350
0  Júnior     Jorge    150
1  Júnior    Carlos    432
2   Pleno   Roberta    190
3   Pleno  Patrícia    230
4  Sênior     Bruno    410
5  Sênior      Vera    155

In [29]:
df3.groupby(["Classe", "Nome"]).sum()

                 Venda
Classe Nome
Júnior Carlos      552
       Jorge       350
Pleno  Patrícia    354
       Roberta     530
Sênior Bruno       653
       Vera        505

# Lendo e Combinando tabelas

## Merge, Concat e Join

### Concat

In [35]:
df1 = pd.DataFrame({'A': ['A0', 'A1','A2', 'A3'],
'B': ['B0', 'B1', 'B2', 'B3'],
'C': ['C0', 'C1', 'C2', 'C3'],
'D': ['D0', 'D1', 'D2', 'D3']},
index=[0,1,2,3])

df2 = pd.DataFrame({'A': ['A4', 'A5','A6', 'A7'],
'B': ['B4', 'B5', 'B6', 'B7'],
'C': ['C4', 'C5', 'C6', 'C7'],
'D': ['D4', 'D5', 'D6', 'D7']},
index=[4,5,6,7])

df3 = pd.DataFrame({'A': ['A8', 'A9','A10', 'A11'],
'B': ['B8', 'B9', 'B10', 'B11'],
'C': ['C8', 'C9', 'C10', 'C11'],
'D': ['D8', 'D9', 'D10', 'D11']},
index=[8,9,10,11])

In [36]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [37]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [38]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [39]:
pd.concat([df1, df2, df3]) ## Similar ao Union do SQL, Acrescentar tabelas em Power Query. Basicamente empilhar dataframes

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

### Merge

In [40]:
esquerda = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
'A': ['A0', 'A1', 'A2', 'A3'],
'B': ['B0', 'B1', 'B2', 'B3']})
esquerda

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [41]:
direita = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
'C': ['C0', 'C1', 'C2', 'C3'],
'D': ['D0', 'D1', 'D2', 'D3']})
direita

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [ ]:
# É possível fazer um merge sem especificar a chave, de tal forma que o pandas vai automaticamente mesclar quanto existirem colunas com o nome igual. É análogo ao NATURAL JOIN em SQL
display(pd.merge(esquerda, direita))

# Também é possível especificar a coluna que vai ser usada no merge como chave, nesse caso redundante, mas nem sempre as colunas vão ter os mesmos nomes
# É comum vir indicando "id" quando for chave primária e "table_name_id" quando for chave estrangeira
display(pd.merge(esquerda, direita, on="key"))

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [49]:
esquerda = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
'key2': ['K0', 'K1', 'K0', 'K1'],
'A': ['A0', 'A1', 'A2', 'A3'],
'B': ['B0', 'B1', 'B2', 'B3']})
esquerda

  key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

In [51]:
direita = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
'key2': ['K0', 'K0', 'K0', 'K0'],
'C': ['C0', 'C1', 'C2', 'C3'],
'D': ['D0', 'D1', 'D2', 'D3']})
direita

  key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [ ]:
# Trabalhando com dados um pouco mais complexos, temos key1 e key2, permitindo executar merges com chaves mistas/compostas.
pd.merge(esquerda, direita, on=['key1', 'key2'])

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [59]:
# Também é possível dizer qual o método de merge que vai ser usado
pd.merge(esquerda, direita, how='outer', on=['key1', 'key2'])

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

### Join

In [60]:
esquerda = pd.DataFrame({'A': ['A0', 'A1','A2'],
'B': ['B0', 'B1', 'B2']},
index=['K0', 'K1', 'K2'])
esquerda

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [62]:
direita = pd.DataFrame({'C': ['C0', 'C2','C3'],
'D': ['D0', 'D2', 'D3']},
index=['K0', 'K2', 'K3'])
direita

     C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [69]:
esquerda.join(direita, how='outer')

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

## Séries Temporais

In [30]:
numero_de_dias = 100

In [36]:
datas = pd.date_range(start='1/1/2021', periods=numero_de_dias)
print(type(datas))
print(datas)

<class 'pandas.DatetimeIndex'>
DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
               '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
               '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
               '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
               '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
               '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
               '2021-01-29', '2021-01-30', '2021-01-31', '2021-02-01',
               '2021-02-02', '2021-02-03', '2021-02-04', '2021-02-05',
               '2021-02-06', '2021-02-07', '2021-02-08', '2021-02-09',
               '2021-02-10', '2021-02-11', '2021-02-12', '2021-02-13',
               '2021-02-14', '2021-02-15', '2021-02-16', '2021-02-17',
               '2021-02-18', '2021-02-19', '2021-02-20', '2021-02-21',
               '2021-02-22', '2021-02-23', '2021-02-24', '2021-02-25',
               '2021-02-26', '2021-02-27', '2021-02-28', '2021-03-01',
               '2021-03-02', '2021-03-03', '2021-03-04', '2021-03-05',
               '2021-03-06', '2021-03-07', '2021-03-08', '2021-03-09',
               '2021-03-10', '2021-03-11', '2021-03-12', '2021-03-13',
               '2021-03-14', '2021-03-15', '2021-03-16', '2021-03-17',
               '2021-03-18', '2021-03-19', '2021-03-20', '2021-03-21',
               '2021-03-22', '2021-03-23', '2021-03-24', '2021-03-25',
               '2021-03-26', '2021-03-27', '2021-03-28', '2021-03-29',
               '2021-03-30', '2021-03-31', '2021-04-01', '2021-04-02',
               '2021-04-03', '2021-04-04', '2021-04-05', '2021-04-06',
               '2021-04-07', '2021-04-08', '2021-04-09', '2021-04-10'],
              dtype='datetime64[us]', freq='D')

In [39]:
df = pd.DataFrame(range(numero_de_dias), columns=["number"], index=datas)
df

            number
2021-01-01       0
2021-01-02       1
2021-01-03       2
2021-01-04       3
2021-01-05       4
...            ...
2021-04-06      95
2021-04-07      96
2021-04-08      97
2021-04-09      98
2021-04-10      99

[100 rows x 1 columns]

In [41]:
df.index

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
               '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
               '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
               '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
               '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
               '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
               '2021-01-29', '2021-01-30', '2021-01-31', '2021-02-01',
               '2021-02-02', '2021-02-03', '2021-02-04', '2021-02-05',
               '2021-02-06', '2021-02-07', '2021-02-08', '2021-02-09',
               '2021-02-10', '2021-02-11', '2021-02-12', '2021-02-13',
               '2021-02-14', '2021-02-15', '2021-02-16', '2021-02-17',
               '2021-02-18', '2021-02-19', '2021-02-20', '2021-02-21',
               '2021-02-22', '2021-02-23', '2021-02-24', '2021-02-25',
               '2021-02-26', '2021-02-27', '2021-02-28', '2021-03-01',
               '2021-03-02', '2021-03-03', '2021-03-04', '2021-03-05',
               '2021-03-06', '2021-03-07', '2021-03-08', '2021-03-09',
               '2021-03-10', '2021-03-11', '2021-03-12', '2021-03-13',
               '2021-03-14', '2021-03-15', '2021-03-16', '2021-03-17',
               '2021-03-18', '2021-03-19', '2021-03-20', '2021-03-21',
               '2021-03-22', '2021-03-23', '2021-03-24', '2021-03-25',
               '2021-03-26', '2021-03-27', '2021-03-28', '2021-03-29',
               '2021-03-30', '2021-03-31', '2021-04-01', '2021-04-02',
               '2021-04-03', '2021-04-04', '2021-04-05', '2021-04-06',
               '2021-04-07', '2021-04-08', '2021-04-09', '2021-04-10'],
              dtype='datetime64[us]', freq='D')

In [43]:
df.index[0]

Timestamp('2021-01-01 00:00:00')

In [44]:
df.index[0].day

1

In [45]:
df.index[0].month

1

In [46]:
df.index[0].year

2021

In [47]:
df.index[0].week

53

In [49]:
df.index[0].weekday()

4

In [50]:
df.index[0].second

0

In [51]:
df.index[0].minute

0

In [52]:
df.index[0].hour

0

In [56]:
df[df.index.weekday == 1]

            number
2021-01-05       4
2021-01-12      11
2021-01-19      18
2021-01-26      25
2021-02-02      32
2021-02-09      39
2021-02-16      46
2021-02-23      53
2021-03-02      60
2021-03-09      67
2021-03-16      74
2021-03-23      81
2021-03-30      88
2021-04-06      95

In [57]:
df["Mês"] = df.index.month

In [58]:
df

            number  Mês
2021-01-01       0    1
2021-01-02       1    1
2021-01-03       2    1
2021-01-04       3    1
2021-01-05       4    1
...            ...  ...
2021-04-06      95    4
2021-04-07      96    4
2021-04-08      97    4
2021-04-09      98    4
2021-04-10      99    4

[100 rows x 2 columns]

In [ ]:
import datetime #datetime é um módulo do pandas para trabalhar com datetime em dataframes

df[df.index > datetime.datetime(2021, 1, 10)]

            number  Mês
2021-01-11      10    1
2021-01-12      11    1
2021-01-13      12    1
2021-01-14      13    1
2021-01-15      14    1
...            ...  ...
2021-04-06      95    4
2021-04-07      96    4
2021-04-08      97    4
2021-04-09      98    4
2021-04-10      99    4

[90 rows x 2 columns]

## Entrada e Saída de Dados

## Operações com Data Frames

In [72]:
df = pd.DataFrame({'col1': [1,2,3,4], 'col2':[444, 555, 666, 444], 'col3': ['abc', 'def', 'ghi', 'xyz']})
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [74]:
df.head() # Para inspeção inicial das colunas e informações

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [ ]:
df.info() # Para extração de meta dados, lista de colunas, contagem de não nulos, tipificação, tamanho em memória. Melhor até que fazer .dtypes em tudo!

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      int64
 1   col2    4 non-null      int64
 2   col3    4 non-null      str
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [78]:
df.memory_usage() # Para identifiação da memória usada por coluna do dataframe

Index    132
col1      32
col2      32
col3      32
dtype: int64

In [80]:
df['col1'].unique() # Identifica os valores únicos em uma series

array([1, 2, 3, 4])

In [85]:
display(df['col1'].nunique()) # Também é possível contar facilmente o número de distintos em uma series

display(df.nunique()) # Esse método também existe para o objeto dataframe, então é possível fazer essa análise em todas as colunas de uma vez

4

col1    4
col2    3
col3    4
dtype: int64

In [89]:
display(df['col3'].value_counts()) # Esse conta quantas ocorrências cada valor da series tem no conjunto de dados

display(df.value_counts()) ## Ele também existe no dataframe, porém ele interpreta cada 'tupla' do dataframe como um valor, então basicamente ele conta linhas únicas e não valores únicos

col3
abc    1
def    1
ghi    1
xyz    1
Name: count, dtype: int64

col1  col2  col3
1     444   abc     1
2     555   def     1
3     666   ghi     1
4     444   xyz     1
Name: count, dtype: int64

## Aplicando funções

É possível aplicar funções em todos os elementos de um dataframe ou de uma series, idêntico a aplicação de uma função em um vetor ou matriz.

In [90]:
def comp(x):
    return x ** 2 + 3

In [ ]:
comp
## Identifica o ponteiro da memória onde a função está

In [ ]:
comp(2)
## Assim eu executo a função

7

In [100]:
df['col2'].apply(comp) ## Usando o método apply, é possível aplicar uma função na lista de valores de uma series

0    197139
1    308028
2    443559
3    197139
Name: col2, dtype: int64

In [103]:
df['col1_calculada'] = df['col2'].apply(comp)
df['col1_calculada']

## Basicamente como colunas calculadas podem ser criadas com métodos de cálculos complexos que são abstraídos e depois executados de forma simples
## Excelente pra criação de métricas de KPIs

0    197139
1    308028
2    443559
3    197139
Name: col1_calculada, dtype: int64

In [105]:
df['col1'].apply(lambda x: x ** 2 + 3) 
# Também é possível aplicar funções lambda

0     4
1     7
2    12
3    19
Name: col1, dtype: int64

É possível aplicar uma série de funções, cálculos e operações simples também.

In [116]:
print("Soma:", df['col1'].sum())

print("Média:", df['col1'].mean())

print("Produto:", df['col1'].product())

print("Desvio Padrão:", df['col1'].std())

print("Máximo:", df['col1'].max())

print("Mínimo:", df['col1'].min())

## Esses dois são do caralho!!! Potencial enorme
print("Índice do valor máximo:", df['col1'].idxmax())
print("Índice do valor mínimo:", df['col1'].idxmin())

print("\n")
print("Soma Cumulativa:\n", df['col1'].cumsum())

Soma: 10
Média: 2.5
Produto: 24
Desvio Padrão: 1.2909944487358056
Máximo: 4
Mínimo: 1
Índice do valor máximo: 3
Índice do valor mínimo: 0


Soma Cumulativa:
 0     1
1     3
2     6
3    10
Name: col1, dtype: int64

In [118]:
df[df["col2"] == 444]["col1"].sum()
# A combinação desses métodos gera possibilidades infinitas para resolução de problemas

np.int64(5)

In [ ]:
display(df.sort_values(by='col2'))
# Também é possível ordenar ou classificar o dataframe por qualquer coluna

display(df.sort_values(by=['col2', 'col1'], ascending=False))
# O filtro pode ser composto e misturado de forma ascendente ou descendente como bem entender

   col1  col2 col3  col1_calculada
0     1   444  abc          197139
3     4   444  xyz          197139
1     2   555  def          308028
2     3   666  ghi          443559

   col1  col2 col3  col1_calculada
2     3   666  ghi          443559
1     2   555  def          308028
3     4   444  xyz          197139
0     1   444  abc          197139