# Series

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
labels = ['a', 'b', 'c'] ## Isso é uma lista

minha_lista = list((10,20,30)) ## Isso também é uma lista, sendo criada por meio da função "list()"

arr = np.array([10,20,30]) ## Isso transforma a lista em um array numpy

d = {'a': 10, 'b': 20, 'c': 30}

In [ ]:
pd.Series(labels) ## Criando uma series a partir de uma lista padrão do python

0    a
1    b
2    c
dtype: str

In [ ]:
pd.Series(data=labels, index=minha_lista) ## Posso manipular a criação dos indíces da minha series a partir de seus parâmetros

10    a
20    b
30    c
dtype: str

In [ ]:
pd.Series(labels, minha_lista) 
## Eu também não preciso dizer os parâmetros se eles estiverem na mesma ordem padrão da assinatura da função.

10    a
20    b
30    c
dtype: str

In [ ]:
d ## A minha variável D é um dicionário

{'a': 10, 'b': 20, 'c': 30}

In [ ]:
pd.Series(d) ## Quando eu passei um dicionário pra criar uma series ele já inferiu que as 'chaves' do dicionário seriam os índices da series

a    10
b    20
c    30
dtype: int64

In [ ]:
series1 = pd.Series([1,2,3,4], index=['Alemanha','Rússia','Estados Unidos','Japão'])
series1

Alemanha          1
Rússia            2
Estados Unidos    3
Japão             4
dtype: int64

In [ ]:
series2 = pd.Series([1,2,5,4], index=['Alemanha','Rússia','Itália','Japão'])
series2

Alemanha    1
Rússia      2
Itália      5
Japão       4
dtype: int64

In [ ]:
series1 + series2

NameError: name 'series1' is not defined

# Dataframe

In [112]:
import numpy as np
import pandas as pd

from numpy.random import randn

In [113]:
df = pd.DataFrame(randn(5, 4), index=["A", "B", "C", "D", "E"], columns="W X Y Z".split())
df

          W         X         Y         Z
A -0.293535 -0.616787  0.944507 -0.161656
B  1.085896 -1.064870  0.462594  0.173990
C  1.006121 -0.420665  0.992359 -2.576258
D  0.024199 -0.279427 -1.102725  0.921637
E  1.531799  1.731191  0.520032 -0.506470

In [114]:
print(df["W"])
type(df["W"])

A   -0.293535
B    1.085896
C    1.006121
D    0.024199
E    1.531799
Name: W, dtype: float64

pandas.Series

In [115]:
print(df[["W", "Y"]])
type(df[["W", "Y"]])

          W         Y
A -0.293535  0.944507
B  1.085896  0.462594
C  1.006121  0.992359
D  0.024199 -1.102725
E  1.531799  0.520032

pandas.DataFrame

In [116]:
df["Novo"] = df["W"]
df

          W         X         Y         Z      Novo
A -0.293535 -0.616787  0.944507 -0.161656 -0.293535
B  1.085896 -1.064870  0.462594  0.173990  1.085896
C  1.006121 -0.420665  0.992359 -2.576258  1.006121
D  0.024199 -0.279427 -1.102725  0.921637  0.024199
E  1.531799  1.731191  0.520032 -0.506470  1.531799

In [117]:
df["Novo"] = df["X"] + df ["Y"]
df

          W         X         Y         Z      Novo
A -0.293535 -0.616787  0.944507 -0.161656  0.327720
B  1.085896 -1.064870  0.462594  0.173990 -0.602276
C  1.006121 -0.420665  0.992359 -2.576258  0.571694
D  0.024199 -0.279427 -1.102725  0.921637 -1.382152
E  1.531799  1.731191  0.520032 -0.506470  2.251224

In [118]:
df["Novo"].drop("A", axis=0) ## Função de DROP similar a cláusula do SQL
## Nesse caso ao fazer df["Novo"] eu estou convertendo e selecionando uma series do meu Dataframe, ao dizer drop("A", axis=0), eu estou selecionando para dropar o índice A eixo 0 que é exatamente a 1ª posição da 1ª (e única coluna)

df[["Novo"]].drop("Novo", axis=1)
# Agora eu preservei o objeto Dataframe porque eu selecionei a coluna "Novo" dentro de uma matriz
# Ao dropar "Novo" eu estou selecionando a coluna toda e o eixo 1 é o eixo das colunas

#df[["Novo"]].drop("Novo", axis=0) -> Não funciona porque axis=0 são os índices pra um DF, não existe o índice "Novo" nesse conjunto de dados, apenas A, B, C...

df[["Novo"]].drop("A", axis=0)
# axis=0 seleciona os índices de um DF, logo, eu consigo acessar e dropar o índice A ou B ou C ou D etc

       Novo
B -0.602276
C  0.571694
D -1.382152
E  2.251224

In [119]:
df ## O Dataframe original não sofreu mudanças porque o drop foi apenas executado pra gerar output e não foi armazenado em nenhuma variável, incluindo a original

          W         X         Y         Z      Novo
A -0.293535 -0.616787  0.944507 -0.161656  0.327720
B  1.085896 -1.064870  0.462594  0.173990 -0.602276
C  1.006121 -0.420665  0.992359 -2.576258  0.571694
D  0.024199 -0.279427 -1.102725  0.921637 -1.382152
E  1.531799  1.731191  0.520032 -0.506470  2.251224

In [120]:
df.drop("A", axis=0, inplace=True)
df
# O parâmetro inplace vai manipular se estou alterando no DF original ou não, caso não queira usar uma nova variável

          W         X         Y         Z      Novo
B  1.085896 -1.064870  0.462594  0.173990 -0.602276
C  1.006121 -0.420665  0.992359 -2.576258  0.571694
D  0.024199 -0.279427 -1.102725  0.921637 -1.382152
E  1.531799  1.731191  0.520032 -0.506470  2.251224

In [121]:
df.loc[["B"]] # Consigo selecionar/localizar/extrair partes específicas assim também

          W        X         Y        Z      Novo
B  1.085896 -1.06487  0.462594  0.17399 -0.602276

In [122]:
df.iloc[0,0] # Trabalha como se fosse um localizador via "coordenada"

np.float64(1.0858963898633254)

# ILoc e Filtros

In [123]:
df
df.loc[["E", "D"],["X", "Z"]]

          X         Z
E  1.731191 -0.506470
D -0.279427  0.921637

In [124]:
df.iloc[:-1] # O ":" denota um invtervalo e o inteiro (1, 2, -1, -2, etc) representa o ponto de início do intervalo, que vai "iterar"/exibir os dados até o fim do data frame
# Valores positivos iniciam do "começo" do DataFrame (1ª linha), valores negativos a partir do "fim" (última linha)

          W         X         Y         Z      Novo
B  1.085896 -1.064870  0.462594  0.173990 -0.602276
C  1.006121 -0.420665  0.992359 -2.576258  0.571694
D  0.024199 -0.279427 -1.102725  0.921637 -1.382152

In [125]:
df.iloc[:1, :3] # Passar um segundo argumento vai denotar a segunda "coordenada" do Data Frame

          W        X         Y
B  1.085896 -1.06487  0.462594

In [126]:
df.iloc[:2, 1:2] # Seleção de lista do tipo "1:2", o 1 é inclusivo e o 2 é exclusivo. Isto é, o que vem antes do ":" inclui o índice 1 e o que vem depois exclui o índice 2

          X
B -1.064870
C -0.420665

In [127]:
df > 0 # Executa uma operação de comparação matricial com um escalar

      W      X      Y      Z   Novo
B  True  False   True   True  False
C  True  False   True  False   True
D  True  False  False   True  False
E  True   True   True  False   True

In [128]:
df[df > 0]
# Eu consigo também fazer seleções que levem em conta comparações lógicas e, além disso, usar dataframes pra selecionar dataframes
# O que tá acontecendo aqui é que o "df > 0" está retornando um dataframe com true e false e o "df[]" está usando isso pra saber que valores selecionar e quais não selecionar

          W         X         Y         Z      Novo
B  1.085896       NaN  0.462594  0.173990       NaN
C  1.006121       NaN  0.992359       NaN  0.571694
D  0.024199       NaN       NaN  0.921637       NaN
E  1.531799  1.731191  0.520032       NaN  2.251224

In [129]:
df

          W         X         Y         Z      Novo
B  1.085896 -1.064870  0.462594  0.173990 -0.602276
C  1.006121 -0.420665  0.992359 -2.576258  0.571694
D  0.024199 -0.279427 -1.102725  0.921637 -1.382152
E  1.531799  1.731191  0.520032 -0.506470  2.251224

In [130]:
df["X"] > 0 # Posso fazer essa mesma manipulação com Series ao invés do dataframe todo

B    False
C    False
D    False
E     True
Name: X, dtype: bool

In [131]:
df[df["X"] > 0] # O índice E foi eliminado da seleção, pois na célula acima o E assume valor falso na comparação, o objeto dataframe está recebendo uma lista de true e false associada aos índices que ele precisa filtrar

          W         X         Y        Z      Novo
E  1.531799  1.731191  0.520032 -0.50647  2.251224

# Operações com Índices

In [132]:
print(df.index) # É possível acessar o índice de um dataframe diretamente como uma lista assim
print(type(df.index))

Index(['B', 'C', 'D', 'E'], dtype='str')
<class 'pandas.Index'>

In [133]:
print(df.columns) # Idem para as colunas, ou a outra dimensão do dataframe
print(type(df.columns))
# Detalhe que tanto as colunas quanto os índices são a mesma classe Index, logo eles são o mesmo construto porém tratados como dimensões diferentes.
# Abstraindo: dimensão A e dimensão B modeladas como classe Index

Index(['W', 'X', 'Y', 'Z', 'Novo'], dtype='str')
<class 'pandas.Index'>

In [134]:
# É possível manipular qual índice é usado

# "Rebaixar" um índice a coluna
print(df.reset_index()) # Agora criou a coluna "index" e índice de fato foi adicionado como sequência numérica

print("\nIsso não grava na memória a operação:\n", df)

# É possível fazer essa mudança "inplace"
# Inplace => gravar na memória a mudança na variável (sem retorno), ao invés de executar o método e gerar um retorno
df.reset_index(inplace=True)
df

  index         W         X         Y         Z      Novo
0     B  1.085896 -1.064870  0.462594  0.173990 -0.602276
1     C  1.006121 -0.420665  0.992359 -2.576258  0.571694
2     D  0.024199 -0.279427 -1.102725  0.921637 -1.382152
3     E  1.531799  1.731191  0.520032 -0.506470  2.251224

Isso não grava na memória a operação:
           W         X         Y         Z      Novo
B  1.085896 -1.064870  0.462594  0.173990 -0.602276
C  1.006121 -0.420665  0.992359 -2.576258  0.571694
D  0.024199 -0.279427 -1.102725  0.921637 -1.382152
E  1.531799  1.731191  0.520032 -0.506470  2.251224

  index         W         X         Y         Z      Novo
0     B  1.085896 -1.064870  0.462594  0.173990 -0.602276
1     C  1.006121 -0.420665  0.992359 -2.576258  0.571694
2     D  0.024199 -0.279427 -1.102725  0.921637 -1.382152
3     E  1.531799  1.731191  0.520032 -0.506470  2.251224

#### Obs.: sobre manipulação de índices em colunas ->

Por mais que não exista um comando "reset_columns", as colunas são índices assim como o que de fato é manipulado no reset_index.

É possível manipular os índices das colunas de duas formas:

##### Cenário 1: O "Truque da Transposição" (Literalmente resetar as colunas)
Se você quer pegar os nomes das suas colunas e transformá-los em uma linha de dados dentro do DataFrame (exatamente o que o reset_index faz com o índice das linhas), a maneira mais criativa e direta é transpor o DataFrame, resetar o índice e transpor de volta.

```python
import pandas as pd

"# Criando um DataFrame simples
df = pd.DataFrame({
    'Matemática': [90, 85],
    'História': [70, 75],
    'Física': [88, 92]
}, index=['Aluno A', 'Aluno B'])

print("--- Original ---")
print(df)

"# O TRUQUE:
"# 1. .T (Transpõe: colunas viram linhas)
"# 2. .reset_index() (O índice - antigas colunas - vira uma coluna de dados)
"# 3. .T (Transpõe de volta)
df_resetado = df.T.reset_index().T

print("\n--- Com Colunas 'Resetadas' para dentro dos dados ---")
print(df_resetado)
```

##### Cenário 2: Achatando Multi-Index (O caso mais comum)
Se você fez um groupby ou uma pivot table, provavelmente acabou com colunas hierárquicas (MultiIndex), onde você tem "níveis" de colunas (ex: ('Vendas', '2023'), ('Vendas', '2024')).

Nesse caso, o "reset" que a maioria das pessoas deseja é achatar esses níveis para ter apenas uma linha de cabeçalho simples.

```python
import pandas as pd

"# Criando um DataFrame com MultiIndex nas colunas (simulando um groupby)
cols = pd.MultiIndex.from_tuples([("Vendas", "Jan"), ("Vendas", "Fev"), ("Lucro", "Jan"), ("Lucro", "Fev")])
data = [[100, 120, 10, 12], [110, 130, 11, 13]]
df_multi = pd.DataFrame(data, columns=cols)

print("--- Original (MultiIndex) ---")
print(df_multi)

"# SOLUÇÃO: Achatar os níveis
"# Isso une os níveis com um sublinhado (ex: Vendas_Jan)
df_multi.columns = ['_'.join(col).strip() for col in df_multi.columns.values]

"# Se quiser apenas remover um nível específico (ex: ficar só com Jan/Fev e ignorar Vendas/Lucro):
"# df_multi.columns = df_multi.columns.get_level_values(1)

print("\n--- Achatado (Nível único) ---")
print(df_multi)
```

## Hierarquia de Índices e índices múltiplos