# Dataframe

In [3]:
import numpy as np
import pandas as pd

from numpy.random import randn

In [4]:
df = pd.DataFrame(randn(5, 4), index=["A", "B", "C", "D", "E"], columns="W X Y Z".split())
df

          W         X         Y         Z
A -0.653574 -1.527426 -1.112802 -0.469387
B -2.327872  0.826121 -0.640723 -0.061643
C  0.822992  0.984600 -0.620740  0.763914
D -0.328036  0.179011  0.324479  1.514704
E -2.350997 -1.090655 -0.480542 -0.702897

In [5]:
print(df["W"])
type(df["W"])

A   -0.653574
B   -2.327872
C    0.822992
D   -0.328036
E   -2.350997
Name: W, dtype: float64

pandas.Series

In [6]:
print(df[["W", "Y"]])
type(df[["W", "Y"]])

          W         Y
A -0.653574 -1.112802
B -2.327872 -0.640723
C  0.822992 -0.620740
D -0.328036  0.324479
E -2.350997 -0.480542

pandas.DataFrame

In [7]:
df["Novo"] = df["W"]
df

          W         X         Y         Z      Novo
A -0.653574 -1.527426 -1.112802 -0.469387 -0.653574
B -2.327872  0.826121 -0.640723 -0.061643 -2.327872
C  0.822992  0.984600 -0.620740  0.763914  0.822992
D -0.328036  0.179011  0.324479  1.514704 -0.328036
E -2.350997 -1.090655 -0.480542 -0.702897 -2.350997

In [8]:
df["Novo"] = df["X"] + df ["Y"]
df

          W         X         Y         Z      Novo
A -0.653574 -1.527426 -1.112802 -0.469387 -2.640228
B -2.327872  0.826121 -0.640723 -0.061643  0.185397
C  0.822992  0.984600 -0.620740  0.763914  0.363859
D -0.328036  0.179011  0.324479  1.514704  0.503490
E -2.350997 -1.090655 -0.480542 -0.702897 -1.571197

In [9]:
df["Novo"].drop("A", axis=0) ## Função de DROP similar a cláusula do SQL
## Nesse caso ao fazer df["Novo"] eu estou convertendo e selecionando uma series do meu Dataframe, ao dizer drop("A", axis=0), eu estou selecionando para dropar o índice A eixo 0 que é exatamente a 1ª posição da 1ª (e única coluna)

df[["Novo"]].drop("Novo", axis=1)
# Agora eu preservei o objeto Dataframe porque eu selecionei a coluna "Novo" dentro de uma matriz
# Ao dropar "Novo" eu estou selecionando a coluna toda e o eixo 1 é o eixo das colunas

#df[["Novo"]].drop("Novo", axis=0) -> Não funciona porque axis=0 são os índices pra um DF, não existe o índice "Novo" nesse conjunto de dados, apenas A, B, C...

df[["Novo"]].drop("A", axis=0)
# axis=0 seleciona os índices de um DF, logo, eu consigo acessar e dropar o índice A ou B ou C ou D etc

       Novo
B  0.185397
C  0.363859
D  0.503490
E -1.571197

In [10]:
df ## O Dataframe original não sofreu mudanças porque o drop foi apenas executado pra gerar output e não foi armazenado em nenhuma variável, incluindo a original

          W         X         Y         Z      Novo
A -0.653574 -1.527426 -1.112802 -0.469387 -2.640228
B -2.327872  0.826121 -0.640723 -0.061643  0.185397
C  0.822992  0.984600 -0.620740  0.763914  0.363859
D -0.328036  0.179011  0.324479  1.514704  0.503490
E -2.350997 -1.090655 -0.480542 -0.702897 -1.571197

In [11]:
df.drop("A", axis=0, inplace=True)
df
# O parâmetro inplace vai manipular se estou alterando no DF original ou não, caso não queira usar uma nova variável

          W         X         Y         Z      Novo
B -2.327872  0.826121 -0.640723 -0.061643  0.185397
C  0.822992  0.984600 -0.620740  0.763914  0.363859
D -0.328036  0.179011  0.324479  1.514704  0.503490
E -2.350997 -1.090655 -0.480542 -0.702897 -1.571197

In [12]:
df.loc[["B"]] # Consigo selecionar/localizar/extrair partes específicas assim também

          W         X         Y         Z      Novo
B -2.327872  0.826121 -0.640723 -0.061643  0.185397

In [13]:
df.iloc[0,0] # Trabalha como se fosse um localizador via "coordenada"

np.float64(-2.3278718273315198)

# ILoc e Filtros

In [16]:
df
df.loc[["E", "D"],["X", "Z"]]

          X         Z
E -1.090655 -0.702897
D  0.179011  1.514704

In [ ]:
df.iloc[:-1] # O ":" denota um invtervalo e o inteiro (1, 2, -1, -2, etc) representa o ponto de início do intervalo, que vai "iterar"/exibir os dados até o fim do data frame
# Valores positivos iniciam do "começo" do DataFrame (1ª linha), valores negativos a partir do "fim" (última linha)

          W         X         Y         Z      Novo
B -2.327872  0.826121 -0.640723 -0.061643  0.185397
C  0.822992  0.984600 -0.620740  0.763914  0.363859
D -0.328036  0.179011  0.324479  1.514704  0.503490

In [44]:
df.iloc[:1, :3] # Passar um segundo argumento vai denotar a segunda "coordenada" do Data Frame

          W         X         Y
B -2.327872  0.826121 -0.640723

In [46]:
df.iloc[:2, 1:2] # Seleção de lista do tipo "1:2", o 1 é inclusivo e o 2 é exclusivo. Isto é, o que vem antes do ":" inclui o índice 1 e o que vem depois exclui o índice 2

          X
B  0.826121
C  0.984600

In [48]:
df > 0 # Executa uma operação de comparação matricial com um escalar

       W      X      Y      Z   Novo
B  False   True  False  False   True
C   True   True  False   True   True
D  False   True   True   True   True
E  False  False  False  False  False

In [50]:
df[df > 0]
# Eu consigo também fazer seleções que levem em conta comparações lógicas e, além disso, usar dataframes pra selecionar dataframes
# O que tá acontecendo aqui é que o "df > 0" está retornando um dataframe com true e false e o "df[]" está usando isso pra saber que valores selecionar e quais não selecionar

          W         X         Y         Z      Novo
B       NaN  0.826121       NaN       NaN  0.185397
C  0.822992  0.984600       NaN  0.763914  0.363859
D       NaN  0.179011  0.324479  1.514704  0.503490
E       NaN       NaN       NaN       NaN       NaN

In [52]:
df

          W         X         Y         Z      Novo
B -2.327872  0.826121 -0.640723 -0.061643  0.185397
C  0.822992  0.984600 -0.620740  0.763914  0.363859
D -0.328036  0.179011  0.324479  1.514704  0.503490
E -2.350997 -1.090655 -0.480542 -0.702897 -1.571197

In [ ]:
df["X"] > 0 # Posso fazer essa mesma manipulação com Series ao invés do dataframe todo

pandas.Series

In [58]:
df[df["X"] > 0] # O índice E foi eliminado da seleção, pois na célula acima o E assume valor falso na comparação, o objeto dataframe está recebendo uma lista de true e false associada aos índices que ele precisa filtrar

          W         X         Y         Z      Novo
B -2.327872  0.826121 -0.640723 -0.061643  0.185397
C  0.822992  0.984600 -0.620740  0.763914  0.363859
D -0.328036  0.179011  0.324479  1.514704  0.503490

# Operações com Índices